name: "Build Container"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: "Build project"
    runs-on: ubuntu-latest
    steps:
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: eu-west-2
#
#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: '18'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          lein: latest

      - name: Download app dependencies
        run: lein deps

      - name: Compile app
        run: mv "$(lein uberjar | sed -n 's/^Created \(.*standalone\.jar\)/\1/p')" app-standalone.jar

#       - name: Build Docker image
#         uses: docker/build-push-action@v2.5.0
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.login-ecr.outputs.registry }}/tdr-prod-algo-trader:${{ github.sha }},${{ steps.login-ecr.outputs.registry }}/tdr-prod-algo-trader:latest
