name: "Build Container"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: "Build project"
    runs-on: ubuntu-latest
    steps:
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: latest

      - name: Compile app with leiningen
        run: mv "$(lein uberjar | sed -n 's/^Created \(.*standalone\.jar\)/\1/p')" app-standalone.jar

      - name: Build Docker image
        uses: docker/build-push-action@v2.5.0
        env:
          #ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tdr-prod-algo-trader
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: .
          push: false
          tags: $ECR_REPOSITORY:$IMAGE_TAG
          # tags: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
