name: "Build Container"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: "Build project"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: latest

      - name: Compile app with leiningen
        run: mv "$(lein uberjar | sed -n 's/^Created \(.*standalone\.jar\)/\1/p')" app-standalone.jar

      - name: Build Docker image
        uses: docker/build-push-action@v2.5.0
        with:
          push: false
          tags: user/app:latest
